title: Voided Depths
description: Notes from an existential programmer.
author: Joseph George
avatar: /pro_pic2.jpg
email: jge9@protonmail.ch

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
 
paginate: 10

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

skin: midnight

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.png
social:
  name: Joseph George
  links:
    - https://github.com/ryll-spectre
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en

plugins:
  - jekyll-remote-theme

remote_theme: zivong/jekyll-theme-hamilton
